# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
data_add = 'output_data/cities.csv'
city_data = pd.read_csv(data_add)
del city_data['Unnamed: 0']
city_data

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,hermanus,-34.42,19.23,51.01,95,58,5.91,ZA,1602985579
1,pisco,-13.70,-76.22,62.01,87,40,13.87,PE,1602985579
2,butaritari,3.07,172.79,82.51,77,23,20.36,KI,1602985580
3,tasiilaq,65.61,-37.64,46.40,42,6,14.99,GL,1602985580
4,severnyy-kospashskiy,59.09,57.80,30.00,92,100,1.99,RU,1602985580
...,...,...,...,...,...,...,...,...,...
554,la ronge,55.10,-105.28,26.60,73,90,19.46,CA,1602985641
555,namibe,-15.20,12.15,69.19,71,58,6.11,AO,1602985654
556,taltal,-25.40,-70.48,58.46,72,6,4.52,CL,1602985618
557,sisimiut,66.94,-53.67,38.17,85,100,15.23,GL,1602985654
558,surt,31.21,16.59,72.88,82,99,13.85,LY,1602985654

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
# Configure gmaps
gmaps.configure(api_key=g_key)

In [4]:
# Store 'Lat' and 'Lng' into  locations 
locations = city_data[["Lat", "Lng"]].astype(float)

# Convert Humidity to float and store
humidity_rate = city_data["Humidity"].astype(float)

#Display Map and Heat Map Overlay
fig = gmaps.figure(map_type='HYBRID',layout={'width': '600px','height': '500px','padding': '3px','border': '1px solid black'})
heat_layer = gmaps.heatmap_layer(locations, weights=humidity_rate, dissipating=False, max_intensity=100, point_radius = 1)
fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(border='1px solid black', height='500px', padding='3px', width='600px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [5]:
#Narrow down the cities to fit weather conditions
high_temp = ['less','Max Temp', 79]
low_temp = ['greater','Max Temp', 60]
humid_max = ['less','Humidity', 50]
clouds = ['greater','Cloudiness', 0]
parameters = [high_temp,low_temp,humid_max,clouds]
vac_cities = city_data.copy()
for i in parameters:
    if i[0] == 'less':
        vac_cities = vac_cities[vac_cities[i[1]] < i[2]]
    else:
        vac_cities = vac_cities[vac_cities[i[1]] > i[2]]
vac_cities

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
124,jiwani,25.05,61.74,76.33,23,100,23.04,PK,1602985597
164,yunhe,34.08,119.72,63.72,46,100,1.79,CN,1602985603
167,bardiyah,31.76,25.09,76.98,40,64,11.65,LY,1602985603
237,springfield,37.22,-93.30,63.00,42,90,13.87,US,1602985592
276,urambo,-5.07,32.05,71.91,48,78,7.81,TZ,1602985618
432,jasper,37.20,-94.35,64.40,36,75,9.17,US,1602985638
468,yulara,-25.24,130.99,78.80,41,95,18.34,AU,1602985604
473,moree,-29.47,149.85,77.00,36,93,8.05,AU,1602985643
508,comodoro rivadavia,-45.87,-67.50,68.00,32,50,17.22,AR,1602985501
514,hede,33.77,120.25,64.65,42,97,2.62,CN,1602985648
535,zhoucheng,35.91,116.31,64.00,1,19,6.67,CN,1602985651

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [6]:
#Create empty list to hold all of the hotel data
hotel_list = []

#Format API request
cities = vac_cities['City']
url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json?"

#Print header for API processing log
print('Beginning Data Retrieval ') 
print('-----------------------------')

#Conduct a series of successive API calls to gather hotel data for vacation cities
for city in cities: 
    print(f'Retrieving Results for City | {city}') 
    df = vac_cities[vac_cities['City'] == city] 
    city_lat = df.iloc[0]['Lat'] 
    city_lng = df.iloc[0]['Lng'] 
    parameters = (f"location={city_lat},{city_lng}&radius=5000&type=lodging&key={g_key}")

#Check to make sure the city has hotel data, if not skip that city and continue
    try:

#Get the response from the API request and capture the hotel data values from the request
        response = requests.get(url + parameters).json()

#extract results
        lodging_name = response['results'][0]['name']
        print(f"Closest hotel is {lodging_name}.")
        hotel_list.append(lodging_name)

#Generate an exception message if hotel data not found
    except Exception:
        print(f'{city} hotel not found. Skipping...')
        
vac_cities['Hotel Name'] = hotel_list
vac_cities

Beginning Data Retrieval
-----------------------------
Retrieving Results for City | jiwani
Closest hotel is Al Mumtaz Transport Jiwani.
Retrieving Results for City | yunhe
Closest hotel is Subei Hotel.
Retrieving Results for City | bardiyah
Closest hotel is Ø¨ÙˆØ±ØªÙˆ Ø¨Ø±Ø¯ÙŠØ©.
Retrieving Results for City | springfield
Closest hotel is Best Western Route 66 Rail Haven.
Retrieving Results for City | urambo
Closest hotel is Fair Lodge.
Retrieving Results for City | jasper
Closest hotel is Guest House Motel.
Retrieving Results for City | yulara
Closest hotel is Desert Gardens Hotel - Ayers Rock Resort.
Retrieving Results for City | moree
Closest hotel is Molika Springs Motel.
Retrieving Results for City | comodoro rivadavia
Closest hotel is Austral Hotel.
Retrieving Results for City | hede
Closest hotel is Vienna 3 Best Hotel Sheyang Jiefang Rd.
Retrieving Results for City | zhoucheng
Closest hotel is Yingbin Restaurant.

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
124,jiwani,25.05,61.74,76.33,23,100,23.04,PK,1602985597,Al Mumtaz Transport Jiwani
164,yunhe,34.08,119.72,63.72,46,100,1.79,CN,1602985603,Subei Hotel
167,bardiyah,31.76,25.09,76.98,40,64,11.65,LY,1602985603,Ø¨ÙˆØ±ØªÙˆ Ø¨Ø±Ø¯ÙŠØ©
237,springfield,37.22,-93.30,63.00,42,90,13.87,US,1602985592,Best Western Route 66 Rail Haven
276,urambo,-5.07,32.05,71.91,48,78,7.81,TZ,1602985618,Fair Lodge
432,jasper,37.20,-94.35,64.40,36,75,9.17,US,1602985638,Guest House Motel
468,yulara,-25.24,130.99,78.80,41,95,18.34,AU,1602985604,Desert Gardens Hotel - Ayers Rock Resort
473,moree,-29.47,149.85,77.00,36,93,8.05,AU,1602985643,Molika Springs Motel
508,comodoro rivadavia,-45.87,-67.50,68.00,32,50,17.22,AR,1602985501,Austral Hotel
514,hede,33.77,120.25,64.65,42,97,2.62,CN,1602985648,Vienna 3 Best Hotel Sheyang Jiefang Rd
535,zhoucheng,35.91,116.31,64.00,1,19,6.67,CN,1602985651,Yingbin Restaurant

In [7]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in vac_cities.iterrows()]
locations = vac_cities[["Lat", "Lng"]]

In [8]:
# Add marker layer using the hotel info to fill the info box ontop of heat map
markers = gmaps.marker_layer(locations,info_box_content=hotel_info)
fig.add_layer(markers)

# Display figure
fig

Figure(layout=FigureLayout(border='1px solid black', height='500px', padding='3px', width='600px'))